services:
  app:
    build:
      context: .
      dockerfile: deployment/php/Dockerfile
    container_name: management_product_app
    volumes:
      - .:/var/www
    depends_on:
      - db
    networks:
      - laravel
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: management_product
      DB_USERNAME: root
      DB_PASSWORD: root

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./deployment/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: management_product_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: management_product
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  pgdata:
